export const BASE_URL = 'https://localhost:7049/api';

export const config = {
    apiUrl: BASE_URL,
  };

  export const soundcloudConfig = {
    clientId: "8BBZpqUP1KSN4W6YB64xog2PX4Dw98b1",
    accessToken: "2-294507-45024505-OGJutYmDr0kE4nt"
  };
  
  export const QUERY_KEY = {
    user: 'user',
    posts: 'posts',
    discussions: 'discussions',
    profile: 'profile'
  };

  export const GENRE_LIST = [
    "(Carolina) Beach Music",
    "2 Tone",
    "2-Step",
    "2-Tone",
    "4-Beat",
    "4x4",
    "8bit",
    "A cappella",
    "Acid Breaks",
    "Acid House",
    "Acid Jazz",
    "Acid Rock",
    "Acid Techno",
    "Acid Trance",
    "Acid-House",
    "Acousmatic Music",
    "Acoustic Blues",
    "Adult Alternative",
    "Adult Contemporary",
    "Adult-Oriented Rock",
    "Africa",
    "African Blues",
    "African Heavy Metal",
    "African Hip Hop",
    "Afro Punk",
    "Afro-Beat",
    "Afro-Cuban Jazz",
    "Afro-House",
    "Afro-Pop",
    "Aggrotech",
    "Alternative Country",
    "Alternative Dance",
    "Alternative Folk",
    "Alternative Rap",
    "Alternative Rock",
    "Alternativo & Rock Latino",
    "Ambient",
    "Ambient Dub",
    "Ambient House",
    "Ambient Techno",
    "American Folk Revival",
    "American Traditional Rock",
    "Americana",
    "Anatolian Rock",
    "Anison",
    "Anti-Folk",
    "Apala",
    "Arab Pop",
    "Arena Rock",
    "Argentine Tango",
    "Art Punk",
    "Art Rock",
    "Asia",
    "Asian Underground",
    "Australia",
    "Australian Country",
    "Austropop",
    "Avant-Garde",
    "Avant-Garde Jazz",
    "Avantgarde Metal",
    "Axé",
    "Bachata",
    "Background",
    "Baggy",
    "Baila",
    "Baithak Gana",
    "Bakersfield Sound",
    "Baladas y Boleros",
    "Balearic Beat",
    "Balkan Pop",
    "Ballet",
    "Baltimore Club",
    "Barbershop",
    "Baroque",
    "Bassline",
    "Bebop",
    "Benga",
    "Berlin School",
    "Bhangra",
    "Bhojpuri",
    "Big Band",
    "Big Beat",
    "Bikutsi",
    "Bitpop",
    "Black Metal",
    "Blue Note",
    "Bluegrass",
    "Blues Country",
    "Blues Rock",
    "Blues Shouter",
    "Blues-Rock",
    "Bolero",
    "Bongo Flava",
    "Boogie",
    "Bop",
    "Bossa Nova",
    "Bounce",
    "Bounce / Scouse House",
    "Bouncy House",
    "Bouncy Techno",
    "Brazilian",
    "Brazilian Rock",
    "Breakbeat / Breakstep",
    "Breakbeat Hardcore",
    "Breakcore",
    "Brega",
    "Brick City Club",
    "British Blues",
    "British Dance Band (Jazz)",
    "British Folk Revival",
    "British Invasion",
    "Britpop",
    "Britpunk",
    "Broken Beat",
    "Brostep",
    "Bubblegum Dance",
    "Bubblegum Pop",
    "C-Pop",
    "CCM",
    "Cajun",
    "Cajun Fiddle Tunes",
    "Calypso",
    "Canadian Blues",
    "Cantata",
    "Cantique",
    "Cantopop",
    "Cape Jazz",
    "Caribbean",
    "Carnatic (Karnataka Sanghetha)",
    "Celtic",
    "Celtic Folk",
    "Chamber Jazz",
    "Chamber Music",
    "Chamber Pop",
    "Chanson",
    "Chant",
    "Chanukah",
    "Chap Hop",
    "Chicago Blues",
    "Chicago Hip Hop",
    "Chicago House",
    "Chicano",
    "Chicha",
    "Chill Out",
    "Chillstep",
    "Chillwave",
    "Chimurenga",
    "Chiptune",
    "Choral",
    "Choro",
    "Christian & Gospel",
    "Christian Country",
    "Christian Hip Hop",
    "Christian Metal",
    "Christian Pop",
    "Christian Rap",
    "Christian Rock",
    "Christmas",
    "Chutney",
    "Chutney Soca",
    "CityPop",
    "Classic",
    "Classic Blues",
    "Classic Christian",
    "Classic Country",
    "Classic Female Blues",
    "Classic Trance",
    "Classical Crossover",
    "Close Harmony",
    "Club / Club Dance",
    "Cock Rock",
    "Coldwave",
    "College Rock",
    "Commercial",
    "Compas",
    "Computer Music",
    "Concerto",
    "Concerto Grosso",
    "Conjunto",
    "Conjunto Progressive",
    "Conscious Hip Hop",
    "Contemporary Bluegrass",
    "Contemporary Blues",
    "Contemporary Celtic",
    "Contemporary Country",
    "Contemporary Folk",
    "Contemporary Gospel",
    "Contemporary Jazz",
    "Contemporary Latin",
    "Contemporary R&B",
    "Contemporary Singer/Songwriter",
    "Continental Jazz",
    "Cool Jazz",
    "Country Blues",
    "Country Gospel",
    "Country Pop",
    "Country Rap",
    "Country Rock",
    "Country Soul",
    "Country-Rap",
    "Coupé-Décalé",
    "Coupé-décalé – Congo",
    "Cowboy / Western",
    "Cowpunk",
    "Criolla",
    "Crossover",
    "Crossover Jazz",
    "Crossover Thrash",
    "Crunk",
    "Crunkcore",
    "Crust Punk",
    "Cumbia",
    "Cumbia Rap",
    "Cybergrind",
    "Dance Pop",
    "Dance-Punk",
    "Dance-Rock",
    "Dance-pop",
    "Dancehall",
    "Dangdut",
    "Dansband",
    "Dark Ambient",
    "Dark Blues",
    "Dark Electro",
    "Dark Jazz",
    "Dark Psy",
    "Dark Psytrance",
    "Dark Wave",
    "Darkcore",
    "Darkside Jungle",
    "Darkstep",
    "Death Industrial",
    "Death Metal",
    "Death Metal / Black Metal",
    "Deathcore",
    "Deep House",
    "Delta Blues",
    "Detroit Blues",
    "Detroit Hip Hop",
    "Detroit Techno",
    "Digital Hardcore",
    "Dirty South",
    "Disco",
    "Disco House",
    "Diva House",
    "Dixieland",
    "Djent",
    "DnB",
    "Doo Wop",
    "Doo-wop",
    "Doom Blues",
    "Doom Metal",
    "Doomcore",
    "Downtempo",
    "Dream House",
    "Dream Pop",
    "Dream Trance",
    "Drinking Songs",
    "Drone",
    "Drone Music",
    "Drum & Bass",
    "Drumfunk",
    "Drumstep",
    "Dub",
    "Dub Music",
    "Dubstep",
    "Dubstyle",
    "Dubtronica",
    "Dutch House",
    "EDM",
    "Early Jazz",
    "Early Music",
    "East Coast",
    "Easter",
    "Electric Blues",
    "Electro",
    "Electro Backbeat",
    "Electro House",
    "Electro Pop",
    "Electro Swing (Jazz)",
    "Electro-Grime",
    "Electro-Industrial",
    "Electro-swing",
    "Electroacoustic",
    "Electroacoustic Improvisation",
    "Electroclash",
    "Electronic Art Music",
    "Electronic Body Music",
    "Electronic Dance Music",
    "Electronic Rock",
    "Electronica",
    "Electronicore",
    "Electropop",
    "Electropunk",
    "Electroswing",
    "Elevator",
    "Emotional Hardcore (emo / emocore)",
    "Enka",
    "Entechno",
    "Environmental",
    "Ethereal Wave",
    "Ethio-jazz",
    "Ethnic Electronica",
    "Ethno-Jazz",
    "Eurobeat",
    "Eurodance",
    "European Free Jazz",
    "Europop",
    "Exercise",
    "Experimental Rock",
    "Expressionist",
    "Fann At-Tanbura",
    "Field Recording",
    "Fijiri",
    "Filk Music",
    "Filmi",
    "Flamenco / Spanish Flamenco",
    "Florida Breaks",
    "Folk Blues",
    "Folk Metal",
    "Folk Music",
    "Folk Punk",
    "Folk-Rock",
    "Folktronica",
    "Foreign Cinema",
    "Forró",
    "France",
    "Franco-Country",
    "Freak Folk",
    "Free Funk (Avant-Garde / Funk Jazz)",
    "Free Jazz",
    "Free Tekno",
    "Freestyle House",
    "Freestyle Music",
    "Freestyle Rap",
    "French House",
    "French Pop",
    "Frevo",
    "Fuji Music",
    "Full on",
    "Funk",
    "Funk Carioca",
    "Funky House",
    "Furniture",
    "Fusion",
    "Future Garage",
    "Futurepop",
    "G-Funk",
    "Gabber",
    "Game Boy",
    "Gangsta Rap",
    "Garage",
    "Genge",
    "Ghetto House",
    "Ghettotech",
    "Glam Metal",
    "Glam Rock",
    "Glitch",
    "Glitch Hop",
    "Glitch Pop",
    "Gnawa (hypnotic trance)",
    "Goa Trance",
    "Golden Age",
    "Gospel",
    "Gospel Blues",
    "Goth / Gothic Rock",
    "Gothic Metal",
    "Gregorian Chant",
    "Grime",
    "Grind Core",
    "Grindcore",
    "Groove Metal",
    "Grunge",
    "Grunk",
    "Gulf and Western",
    "Gypsy Jazz",
    "Hair Metal",
    "Halloween",
    "Happy Hardcore",
    "Hard Bop",
    "Hard Dance",
    "Hard Nrg",
    "Hard Rock",
    "Hard Trance",
    "Hardbag",
    "Hardcore",
    "Hardcore Hip Hop",
    "Hardcore Punk",
    "Hardcore Rap",
    "Hardstep",
    "Hardstyle",
    "Harmonica Blues",
    "Hawaii",
    "Healing",
    "Heavy Metal",
    "Hellbilly Music",
    "Hi-NRG / Eurodance",
    "Hi-Nrg",
    "High Classical",
    "Highlife",
    "Hill Country Blues",
    "Hindustani",
    "Hip House",
    "Hip Pop",
    "Hip-Hop",
    "Hiplife",
    "Hokum Blues",
    "Holiday: Other",
    "Hong Kong English Pop",
    "Honky Tonk",
    "Horrorcore",
    "House",
    "Huayno",
    "Hyphy",
    "Hyponagogic",
    "IDM/Experimental",
    "Idm",
    "Illbient",
    "Impressionist",
    "Indian Ghazal",
    "Indian Pop",
    "Indie Folk",
    "Indie Rock",
    "Indietronica",
    "Indo Jazz",
    "Industrial",
    "Industrial Folk",
    "Industrial Hip Hop",
    "Industrial Metal",
    "Industrial Rock",
    "Instrumental Country",
    "Instrumental Hip Hop",
    "Intelligent Drum and Bass",
    "Iranian Pop",
    "Isicathamiya",
    "Isolationism",
    "Italo Dance",
    "Italo House",
    "J-Pop",
    "J-Punk",
    "J-Rock",
    "J-Ska",
    "J-Synth",
    "Jackin House",
    "Jam Bands",
    "Jangle Pop",
    "Japan",
    "Japanese House",
    "Japanese Pop",
    "Japanoise",
    "Jazz Blues",
    "Jazz Rap",
    "Jazz Rock",
    "Jazz-Funk",
    "Jazz-Funk (see Free Funk)",
    "Jazz-Fusion",
    "Jingles",
    "Jit",
    "Joropo",
    "Jump Blues",
    "Jump-Up",
    "Jumpstyle",
    "Jungle",
    "Jùjú",
    "K-Pop",
    "Kansas City Blues",
    "Kansas City Jazz",
    "Kapuka",
    "Kawaii Metal",
    "Kayōkyoku",
    "Khaliji",
    "Kizomba",
    "Klezmer",
    "Korean Pop",
    "Kuduro",
    "Kwaito",
    "Kwela",
    "Laiko",
    "Lambada",
    "Laptronica",
    "Latin Ballad",
    "Latin House",
    "Latin Jazz",
    "Latin Pop",
    "Latin Rap",
    "Lavani",
    "Laïkó",
    "Levenslied",
    "Lingala (Rumba Lingala / Congolese Rumba)",
    "Liquid Dub",
    "Liquid Funk",
    "Live Coding",
    "Live Electronics",
    "Liwa",
    "Lo-fi",
    "Louisiana Blues",
    "Louisiana Swamp Pop",
    "Lounge",
    "Love Song",
    "Lovers Rock",
    "Low Bap",
    "Lowercase",
    "Lubbock Sound",
    "Luk Krung",
    "Luk Thung",
    "Lullabies",
    "Lyrical Hip Hop",
    "M-Base Jazz",
    "Madchester",
    "Mafioso Rap",
    "Mainstream Jazz",
    "Makina",
    "Makossa",
    "Mallsoft",
    "Maloya",
    "Mambo",
    "Mambo (Cuba)",
    "Mandopop",
    "Manila Sound",
    "Maracatu",
    "March (Marching Band)",
    "Mariachi",
    "Marrabenta",
    "Mass Requiem",
    "Math Metal",
    "Math Rock",
    "Mathcore",
    "Mbalax",
    "Mbaqanga",
    "Mbube",
    "Medieval",
    "Meditation",
    "Memphis Blues",
    "Merengue",
    "Merengue Típico",
    "Merenrap",
    "Metal",
    "Metal Core",
    "Metalcore",
    "Mexican Pop",
    "Middle East",
    "Middle of the Road",
    "Midwest Hip Hop",
    "Minimal",
    "Minimal House",
    "Minimal Techno",
    "Minimalism",
    "Modal Jazz",
    "Modern Blues",
    "Modern Classical",
    "Modern Composition",
    "Modern Metal",
    "Modern Soul",
    "Moombahton",
    "Morlam",
    "Morna",
    "Motorpop",
    "Motown",
    "Motswako",
    "Movie Soundtrack",
    "Museve",
    "Musicals",
    "Musique Concrète",
    "Méringue",
    "Música Popular Brasileira",
    "Música Sertaneja",
    "NY Blues",
    "Nashville Sound",
    "Nature",
    "Nederpop",
    "Negro Spiritual",
    "Neo-Bop",
    "Neo-Soul",
    "Neo-Swing",
    "Neoclassical Metal",
    "Neofolk",
    "Neotraditional Country",
    "Nerdcore",
    "Neue Deutsche Härte",
    "Neurofunk",
    "New Acoustic",
    "New Beat",
    "New Jack Swing",
    "New Jersey Hip Hop",
    "New Mex",
    "New Orlean Blues",
    "New Rave",
    "New Romanticism",
    "New School Hip Hop",
    "New Wave",
    "New Wave Of British Heavy Metal",
    "Nintendocore",
    "Noise",
    "Noise Rock",
    "Nortec",
    "North America",
    "Northern Soul",
    "Novelty",
    "Nu Jazz",
    "Nu Metal",
    "Nu Skool Breaks",
    "Nuevo Flamenco",
    "Ode",
    "Old School Rap",
    "Oldschool Jungle:",
    "Onkyokei",
    "Opera",
    "Oratorio",
    "Orchestral",
    "Orchestral Jazz",
    "Orchestral Pop",
    "Orchestral Uplifting",
    "Organum",
    "Original Score",
    "Outlaw Country",
    "Pagan Metal",
    "Pagode",
    "Palm-Wine",
    "Parody Music",
    "Piano Blues",
    "Piedmont Blues",
    "Pinoy Pop",
    "Piphat",
    "Pirate Metal",
    "Polka",
    "Pop Latino",
    "Pop Punk",
    "Pop Rap",
    "Pop Sunda",
    "Pop/Rock",
    "Popera",
    "Portuguese Fado",
    "Post Hardcore",
    "Post Metal",
    "Post Punk",
    "Post Rock",
    "Post-Bop",
    "Post-Disco",
    "Power Electronics",
    "Power Metal",
    "Power Noise",
    "Power Pop",
    "Praise & Worship",
    "Prog-Rock/Art Rock",
    "Prog. Trance",
    "Progressive",
    "Progressive Bluegrass",
    "Progressive Breaks",
    "Progressive Drum & Bass",
    "Progressive Folk",
    "Progressive House",
    "Progressive House / Trance",
    "Progressive Metal",
    "Progressive Rock",
    "Progressive Techno",
    "Protovapor",
    "Psy-Trance",
    "Psybreaks",
    "Psychedelic",
    "Psychedelic Folk",
    "Psychedelic Pop",
    "Psychedelic Soul",
    "Psychobilly / Punkabilly",
    "Psyprog",
    "Punk",
    "Punk Blues",
    "Punk Jazz",
    "Punta",
    "Punta Rock",
    "Qawwali",
    "Quiet Storm",
    "Ragga",
    "Ragga Jungle",
    "Raggacore",
    "Raggamuffin",
    "Ragini",
    "Ragtime",
    "Ragtime Blues",
    "Raison",
    "Ranchera",
    "Rap",
    "Rave Music",
    "Raíces",
    "Raï",
    "Reactionary Bluegrass",
    "Rebetika",
    "Red Dirt",
    "Reggae 110",
    "Reggae Bultrón",
    "Reggae Dancehall",
    "Reggae Fusion",
    "Reggae en Español",
    "Reggaeton y Hip-Hop",
    "Regional Mexicano",
    "Regstep",
    "Relaxation",
    "Renaissance",
    "Rhythm Blues",
    "Rock & Roll",
    "Rocksteady",
    "Romantic (early period)",
    "Romantic (later period)",
    "Romantic Flow",
    "Roots Reggae",
    "Roots Rock",
    "Russian Pop",
    "Sakara",
    "Salsa y Tropical",
    "Samba",
    "Samba Rock",
    "Sambass",
    "Sawt",
    "Schlager",
    "Schranz",
    "Sega",
    "Seggae",
    "Semba",
    "Sertanejo",
    "Shoegaze",
    "Sing-Along",
    "Singer/Songwriter",
    "Ska",
    "Ska Jazz",
    "Skiffle",
    "Skweee",
    "Sludge",
    "Smooth Jazz",
    "Soca",
    "Soft Rock",
    "Son",
    "Sonata",
    "Sophisti-Pop",
    "Soukous",
    "Soul",
    "Soul Blues",
    "Soul Jazz",
    "Sound Art",
    "Soundscape Composition",
    "Soundtrack",
    "South / Southeast Asia",
    "South Africa",
    "South America",
    "Southern Gospel",
    "Southern Rock",
    "Southern Soul",
    "Space Age Pop",
    "Space House",
    "Space Rock",
    "Spanish Reggae",
    "Spazzcore",
    "Speed Garage",
    "Speed Metal",
    "Speedcore",
    "St. Louis Blues",
    "St. Louis Hip Hop",
    "Stand-up Comedy",
    "Standards",
    "Steampunk",
    "Stoner Metal",
    "Stories",
    "Straight-Ahead Jazz",
    "String Quartet",
    "Sung Poetry",
    "Sunshine Pop",
    "Suomisaundi",
    "Surf",
    "Surf Pop",
    "Swamp Blues",
    "Swing",
    "Swing House",
    "Swing Jazz",
    "Symphonic",
    "Symphonic Metal",
    "Symphony",
    "Synthcore",
    "Synthpop",
    "Synthpunk",
    "T-Pop (Thai pop)",
    "TV Soundtrack",
    "TV Themes",
    "Taarab",
    "Taiwanese Pop",
    "Tape Music",
    "Tech House",
    "Tech Trance",
    "Technical Death Metal",
    "Techno",
    "Techno-Dnb",
    "Techno-Folk",
    "Technopop",
    "Techstep",
    "Tecno Brega",
    "Tecnobrega",
    "Teen Pop",
    "Tejano",
    "Terrorcore",
    "Tex-Mex",
    "Texas Blues",
    "Texas County",
    "Thai Pop",
    "Thanksgiving",
    "Third Stream",
    "Thrash Metal",
    "Timba",
    "Time Lord Rock (Trock)",
    "Toytown Techno",
    "Trad Jazz",
    "Traditional Bluegrass",
    "Traditional Celtic",
    "Traditional Country",
    "Traditional Folk",
    "Traditional Gospel",
    "Traditional Pop",
    "Traditional Pop Music",
    "Trance",
    "Trap",
    "Travel",
    "Tribal House",
    "Trip Hop",
    "Trip-hop",
    "Tropical House",
    "Tropicalia",
    "Truck-Driving Country",
    "Turbofolk",
    "Turkish Pop",
    "Turntablism",
    "Twelve-tone",
    "Twin Cities Hip Hop",
    "Twoubadou",
    "UK Garage",
    "UK Hard House",
    "US Garage",
    "Uk Hardcore",
    "Underground Rap",
    "Uplifting Trance",
    "Urban Blues",
    "Urban Cowboy",
    "Vallenato",
    "Vandeville",
    "Vaporhop",
    "Vaportrap",
    "Vaporwave",
    "Vaudeville",
    "Vektroid",
    "Video Game Music",
    "Viking Metal",
    "Vispop",
    "Vocal House",
    "Vocal Jazz",
    "Vocal Pop",
    "Vocal Trance",
    "Wedding Music",
    "West Coast Blues",
    "West Coast Jazz",
    "West Coast Rap",
    "Western Swing",
    "Witch House",
    "Wonky Pop",
    "Worldbeat",
    "Yacht Rock (soft rock)",
    "Yodel",
    "Yorkshire Bleeps and Bass",
    "Zouglou",
    "Zouk",
    "Zouk-Lambada",
    "Zydeco",
  ]